title: The Amor Fati - Blog Home
description: Brain dump of happenings that amuse me.
theme: minima
 Error: (/github/workspace/./_config.yml): mapping values are not allowed in this context at line 1 column 21
